//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kumari_Cinema
{


    public partial class _Default
    {
        protected global::System.Web.UI.WebControls.Label lblMovies;
        protected global::System.Web.UI.WebControls.Label lblTickets;
        protected global::System.Web.UI.WebControls.Label lblUsers;
        protected global::System.Web.UI.WebControls.Label lblShows;
        protected global::System.Web.UI.WebControls.GridView gvTopMovies;
        protected global::System.Web.UI.WebControls.GridView gvRevenue;
        protected global::System.Web.UI.WebControls.GridView gvRecentBookings;
        protected global::System.Web.UI.WebControls.Repeater rptMonthChart;
    }
}
